#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  reaping_frequency: 10
  timeout: 5000

development:
  <<: *default
  database: trekhub_development

test:
  <<: *default
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: trekhub_test

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: trekhub_production
  username: <%= ENV["AWS_DB_USERNAME"] %>
  password: <%= ENV['AWS_DB_PASSWORD'] %>
  host: <%= ENV["AWS_DB_HOST"] %>
  port: 5432
