# This file was generated by the `rails generate rspec:install` command.
require 'codeclimate-test-reporter'
CodeClimate::TestReporter.start
require 'simplecov'
require 'capybara/rspec'
require 'capybara/poltergeist'
require 'pundit/rspec'
require 'devise'

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end

SimpleCov.start 'rails' do
   add_filter 'policy/application_policy.rb'
end